### ISSUE TITLE
Can not change images without loosing all focus points

### ISSUE THREAD

**Issue by pixelbrackets** [xima-media/xima-typo3-manual#47]
Sometimes I need to change an image in an existing manual. When I want to do this for an image in the "Focus Point" content element, all used focus points are removed. I need to add create all squares, type selctions, titles and descriptions again. Is there a better way preserve this focus point "meta data"?

A workaround is to replace the exact same image in the fileadmin using the exact same filename etc... But this is a impractical workflow.

**Comment by maikschneider** [comment]
Thanks for reporting. I think this is an issue for the `bw_focuspoint_images` extension: I added a issue over there: https://github.com/maikschneider/bw_focuspoint_images/issues/29
